INSERT INTO CANDIDATO(CPF, DATA_NASCIMENTO, DESCRICAO, NOME, PRETENSAO) VALUES('42442691850', TO_DATE('31/10/2000', 'DD/MM/YYYY'), 'DESENVOLVEDOR JAVA', 'GUILHERME SENA DA SILVA', 5200);
INSERT INTO CONHECIMENTO(NOME) VALUES('JAVA');
INSERT INTO CONHECIMENTO(NOME) VALUES('SPRING');
INSERT INTO CONHECIMENTO(NOME) VALUES('DOCKER');
INSERT INTO CONHECIMENTO(NOME) VALUES('LINUX');
INSERT INTO CONHECIMENTO(NOME) VALUES('SQL');
INSERT INTO CONHECIMENTO(NOME) VALUES('JENKINS');

INSERT INTO CANDIDATO_CONHECIMENTOS VALUES(1,1);
INSERT INTO CANDIDATO_CONHECIMENTOS VALUES(1,2);
INSERT INTO CANDIDATO_CONHECIMENTOS VALUES(1,3);
INSERT INTO CANDIDATO_CONHECIMENTOS VALUES(1,4);
INSERT INTO CANDIDATO_CONHECIMENTOS VALUES(1,5);